CREATE TABLE Developer (
user INTEGER NOT NULL,
project INTEGER NOT NULL
);
CREATE TABLE Project (
id INTEGER PRIMARY KEY ,
owner INTEGER NOT NULL,
name VARCHAR(32) NOT NULL UNIQUE,
license VARCHAR(20) NOT NULL,
description TEXT NOT NULL,
website VARCHAR(100) NOT NULL,
version INT,
downloads INT NOT NULL
);
CREATE TABLE Tag (
id INTEGER  PRIMARY KEY ,
tag VARCHAR(32) NOT NULL,
project INTEGER NOT NULL
);
CREATE TABLE User (
id INTEGER  PRIMARY KEY ,
fullname VARCHAR(50) NOT NULL,
pass VARCHAR(32) NOT NULL,
email VARCHAR(50) NOT NULL
);
CREATE TABLE Version (
id INTEGER  PRIMARY KEY ,
project INTEGER NOT NULL,
downloads INTEGER NOT NULL,
date VARCHAR(19) NOT NULL,
name VARCHAR(32) NOT NULL,
comments TEXT NOT NULL,
documentation TEXT NULL
);

CREATE INDEX TagSearch ON Tag(tag);
